services:

  db:
    image: pgvector/pgvector:pg16
    container_name: telrag_pgvector
    restart: always
    volumes:
      - telrag-pgvector-volume:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: telrag_redis
    restart: always

  app:
    # the dir which DockerFile is located
    build: .
    container_name: telrag_app
    working_dir: /usr/src/app
    restart: always
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    command: daphne -b 0.0.0.0 -p 8000 django_project.asgi:application
    volumes:
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
      - ./report_result:/usr/src/app/src/data/knowledge_base/telmart/result
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
  # the same dir for the app, as celery uses the app for running and installed inside the django app
    build: .
    container_name: telrag_celery
    working_dir: /usr/src/app
    command: celery -A django_project worker -l info
    restart: always
    depends_on:
      - redis
      - db
      - app


  flower:
    build: .
    container_name: telrag_flower
    working_dir: /usr/src/app
    command: celery -A django_project flower
    restart: always
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db
      - app
      - celery


  alloy:
    image: grafana/alloy:latest
    container_name: telrag_alloy
    volumes:
      - ./.config/alloy.hcl:/etc/alloy/config.hcl
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["run", "/etc/alloy/config.hcl"]

  loki:
    image: grafana/loki:latest
    container_name: telrag_loki

  prometheus:
    image: prom/prometheus:latest
    container_name: telrag_prometheus
    volumes:
      - "./.config/prometheus.yml:/etc/prometheus/prometheus.yml" #prometheus configuration file
      - "prometheus-data:/prometheus" # prometheus data
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: telrag_grafana
    env_file:
      - .env
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki


  caddy:
    image: caddy:latest
    container_name: telrag_caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      DOMAIN: ${DOMAIN}
      GF_DOMAIN: ${GF_DOMAIN}

    volumes:
      - ./src/static_cdn:/srv/telrag/static:ro
      - ./src/media_cdn:/srv/telrag/media:ro
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - app
      - db
      - grafana
      - flower


volumes:
  telrag-pgvector-volume:
  prometheus-data:
  grafana_data:
  caddy_data:
  caddy_config:

