FROM python:3.12-slim

WORKDIR /app

# install uv
RUN pip install uv

# copy dependency files first (docker cache optimization)
COPY pyproject.toml uv.lock ./

# install dependencies
RUN uv sync --frozen

# copy project
COPY project /app

ENV PYTHONUNBUFFERED=1