# Generated by Django 6.0.1 on 2026-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('text', 'Text'), ('video', 'Video')], default='text'),
        ),
        migrations.AddField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG'), ('gif', 'GIF'), ('txt', 'TXT')], default='txt'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
