# Generated by Django 6.0.1 on 2026-02-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_document_content_type_document_format_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
    ]
