# Generated by Django 6.0.1 on 2026-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_remove_document_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
