# Generated by Django 6.0.1 on 2026-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_remove_chunk_document_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG'), ('gif', 'GIF'), ('txt', 'TXT')], default='txt')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
