"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
import socket

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if int(os.getenv("DEBUG")) == 1 else False
PUBLIC = True if int(os.getenv("PUBLIC")) == 1 else False
DOCKER = True if int(os.getenv("DOCKER")) == 1 else False


ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(',')
if DEBUG:
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'debug_toolbar',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'markdown',
    'core',
    'chat',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Required for django toolbar to work properly
INTERNAL_IPS = [
    "127.0.0.1",
]

# Required in case you have app running in docker compose
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS += [ip[:-1] + "1" for ip in ips]

# WSGI_APPLICATION = 'django_project.wsgi.application'

ASGI_APPLICATION = 'django_project.asgi.application'

REDIS_HOST_NAME = os.getenv("REDIS_HOST_NAME") if DOCKER else "localhost"

CHANNEL_LAYERS = {
    # In-memory backend
    # 'default': {
    #     'BACKEND': 'channels.layers.InMemoryChannelLayer',
    # },

    # Redis Backend
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{REDIS_HOST_NAME}:6379/0"],
        },
    },
}


POSTGRES_PORT =  os.getenv("POSTGRES_PORT",5432) if DOCKER else 5433
HOST = os.getenv("HOST") if DOCKER else "localhost"

DATABASES = {
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': HOST,
        'PORT': POSTGRES_PORT,
}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)  
STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]  
  
# Media files (Uploaded by users)  
MEDIA_URL = '/media/'  
MEDIA_ROOT = BASE_DIR / 'media'

# User settings
AUTH_USER_MODEL = 'core.user'




# Source - https://stackoverflow.com/a/7061358
# Posted by Stu, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-18, License - CC BY-SA 4.0

LOGIN_REDIRECT_URL = 'home'


# Demo Settings
DEMO = True

# Celery

CELERY_BROKER_URL = f"redis://{REDIS_HOST_NAME}:6379/1"

# Celery Configuration to avoid memory leak:
CELERY_TASK_TIME_LIMIT = 300  # Hard limit: kills the task if it runs longer than 300 seconds (prevents stuck/hanging tasks)

CELERY_TASK_SOFT_TIME_LIMIT = 240  # Soft limit: sends an exception at 240s so you can gracefully handle cleanup before hard kill

CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restarts worker process after 50 tasks to prevent memory leaks and long-term RAM growth (important for OOM issues)

CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Limits each worker to fetch 1 task at a time (reduces memory spikes and improves fairness across workers)


# CSRF trusted origins for production


csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]

if PUBLIC:
    ngrok_csrf_trusted = os.getenv("NGROK_URL")
    CSRF_TRUSTED_ORIGINS.append(ngrok_csrf_trusted)

# Logging Configuration for alloy
# When we send output using the console, it means we do not need to mount any log files. We can read the logs directly by accessing the shell environment of the running Docker container.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter", # Using json formatter as main json formatting class, this is neccessary to be able to parse valid json in a tool like grafana and using logql commands.
            "format": "%(levelname)s %(message)s %(name)s %(asctime)s",
            "rename_fields": {
                "levelname": "level",
                "message": "msg",
                "name": "logger",
                "asctime": "time",
            },
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",# StreamHandler is for streaming , FileHandler is for file creating
            "formatter": "json",
        },
        # we dont have 'file' handler as we just need send to the out logic, stdout
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Removing django warnings:
"""
chat.Message: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ChatConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
"""
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'