"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta


APP_NAME = "telrag"
ENV_PATH = f".env"
print(f'Envorimental Var Path: {ENV_PATH}')


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%tikckhl@8hyq3$m)aswe4avl+*x^=nc!e-8s0tdoicv-s!j1!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if int(os.getenv("DEBUG")) == 1 else False
DOCKER = True if int(os.getenv("DOCKER")) == 1 else False

ALLOWED_HOSTS = ['secluded-noncongregative-noelle.ngrok-free.dev','127.0.0.1','telrag.site','https://telrag.site']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'markdown',
    'core',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'django_project.wsgi.application'

ASGI_APPLICATION = 'django_project.asgi.application'

REDIS_HOST_NAME = os.getenv("REDIS_HOST_NAME") if DOCKER else "localhost"

CHANNEL_LAYERS = {
    # 'default': {
    #     'BACKEND': 'channels.layers.InMemoryChannelLayer',
    # },
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{REDIS_HOST_NAME}:6379/0"],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

POSTGRES_PORT =  os.getenv("POSTGRES_PORT",5432) if DOCKER else 5433
HOST = os.getenv("HOST") if DOCKER else "localhost"

DATABASES = {
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': HOST,
        'PORT': POSTGRES_PORT,
}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)  
STATIC_URL = '/static/'  
STATIC_ROOT = BASE_DIR/ 'static_cdn'  
STATICFILES_DIRS = [BASE_DIR / "static"]  
  
# Media files (Uploaded by users)  
MEDIA_URL = '/media/'  
MEDIA_ROOT = BASE_DIR / 'media_cdn'

# User settings
AUTH_USER_MODEL = 'core.user'




# Source - https://stackoverflow.com/a/7061358
# Posted by Stu, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-18, License - CC BY-SA 4.0

LOGIN_REDIRECT_URL = 'home'


# Telegram settings

# Telegram webhook security
# Set in .env: strong random string (1–256 chars, A-Za-z0-9_-). When setting webhook
# via setWebhook, pass this as secret_token so Telegram sends it in every request.
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET', '')

# Comma-separated Telegram user IDs allowed to use the bot (e.g. "120358726,123456789").
# If empty, all Telegram users are allowed; set this to restrict to admins only.
def allowed_telegram_ids():
    ids = []
    for x in os.getenv('TELEGRAM_ALLOWED_USER_IDS', '').split(','):
        if x.strip().isdigit():
            ids.append(int(x.strip()))
    return ids

TELEGRAM_ALLOWED_USER_IDS = allowed_telegram_ids()

# https://api.telegram.org/bot<YOUR_TOKEN>/setWebhook?url=https://yourserver.com/hook&secret_token=YOUR_SECRET_STRING

TELEGRAM_DEFAULT_CHAT_ID=120358726


# Demo Settings
DEMO = True

# Celery

CELERY_BROKER_URL = f"redis://{REDIS_HOST_NAME}:6379/1"
CELERY_BEAT_SCHEDULE = {
    "task_delete_unused_conversation" :{
        'task' : 'chat.tasks.task_delete_unused_conversation',
        'schedule' : timedelta(minutes=10)
    }
}



# CSRF trusted origins for production 
ngrok_csrf_trusted = 'https://secluded-noncongregative-noelle.ngrok-free.dev'

csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]

CSRF_TRUSTED_ORIGINS.append(ngrok_csrf_trusted)

# Logging Configuration for alloy
# when we send to out, using console, means that we do not need mount any log file, we can read them thrugh docker container access to the shell envoironment of the running container
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "format": '{"level": "%(levelname)s", "msg": "%(message)s", "logger": "%(name)s", "time": "%(asctime)s"}',
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",# StreamHandler is for streaming , FileHandler is for file creating
            "formatter": "json",
        },
        # we dont have 'file' handler as we just need send to the out logic, stdout
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}