services:
  app:
    networks:
      - caddy-network

  grafana:
    networks:
      - caddy-network

  flower:
    networks:
      - caddy-network
      
networks:
  caddy-network:
    external: true