# Generated by Django 6.0.1 on 2026-01-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_chat_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_group',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatgroup'),
            preserve_default=False,
        ),
    ]
