# Generated by Django 6.0.1 on 2026-02-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_agent',
        ),
    ]
