# Generated by Django 6.0.1 on 2026-02-07 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.document'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chunk'),
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.telegrammessage'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
    ]
