# Generated by Django 6.0.1 on 2026-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
