# Generated by Django 6.0.1 on 2026-01-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_chat_group_message_conversation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGroup',
            new_name='Conversation',
        ),
    ]
