# Generated by Django 6.0.1 on 2026-02-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_agenmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='UserMessage',
        ),
    ]
