# Generated by Django 6.0.1 on 2026-02-09 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_document_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chat.usermessage'),
            preserve_default=False,
        ),
    ]
