# Generated by Django 6.0.1 on 2026-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_message_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
