# Generated by Django 6.0.1 on 2026-02-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_document_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.usermessage'),
        ),
    ]
