# Generated by Django 6.0.1 on 2026-02-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usermessage_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.BooleanField(default=False)),
                ('json_content', models.JSONField()),
            ],
        ),
    ]
