# Generated by Django 6.0.1 on 2026-02-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
