# Generated by Django 6.0.1 on 2026-02-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_agent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
