# Generated by Django 6.0.1 on 2026-02-11 21:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messagegroup_usermessage_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
