# Generated by Django 6.0.1 on 2026-02-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_embedding_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embedding',
            old_name='embedding',
            new_name='vector',
        ),
    ]
