# Generated by Django 6.0.1 on 2026-02-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_embedding_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.messagegroup'),
        ),
    ]
