# Generated by Django 6.0.1 on 2026-02-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_usermessage_message_group'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='telegram_message',
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('direct', 'Direct'), ('telegram', 'Telegram')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.documentsource'),
        ),
    ]
