# Generated by Django 6.0.1 on 2026-02-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_audiocontent_insert_textcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='format',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
    ]
