# Generated by Django 6.0.1 on 2026-02-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_document_file_remove_document_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsource',
            name='name',
        ),
    ]
