# Generated by Django 6.0.1 on 2026-02-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_documentsource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='insert_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.insert'),
        ),
    ]
