# Generated by Django 6.0.1 on 2026-02-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_document_insert_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='insert_method',
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.telegrammessage'),
        ),
        migrations.DeleteModel(
            name='Insert',
        ),
    ]
