# Generated by Django 6.0.1 on 2026-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_remove_document_insert_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='message_group',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AgenMessage',
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
    ]
