# Generated by Django 6.0.1 on 2026-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_usermessage_message_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Message',
        ),
    ]
