# Generated by Django 6.0.1 on 2026-02-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_usermessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocontent',
            name='format',
        ),
        migrations.AddField(
            model_name='audiocontent',
            name='trascription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiocontent',
            name='file',
            field=models.FileField(upload_to='voices'),
        ),
    ]
