# Generated by Django 6.0.2 on 2026-02-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_telegramchatid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramChatID',
        ),
    ]
