# Generated by Django 6.0.2 on 2026-02-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_telegramchatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchatid',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
    ]
