# Generated by Django 6.0.2 on 2026-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_telegramchatid_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchatid',
            name='chat_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
