# Generated by Django 6.0.2 on 2026-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_telegramchatid_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatid',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
