# Generated by Django 6.0.2 on 2026-02-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_telegramchatid_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatid',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
