# Generated by Django 6.0.2 on 2026-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_telegramchatid_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='chat.message'),
        ),
    ]
