# Generated by Django 6.0.2 on 2026-02-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_document_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatid',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
