# Generated by Django 6.0.2 on 2026-03-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_telegramchatid_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.message'),
        ),
    ]
