# Generated by Django 6.0.2 on 2026-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_alter_document_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
