# Generated by Django 6.0.2 on 2026-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_telegrammessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='chat_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
