# Generated by Django 6.0.1 on 2026-03-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_telegrammessage_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
            preserve_default=False,
        ),
    ]
