# Generated by Django 6.0.1 on 2026-03-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_document_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TelegramChatID',
        ),
    ]
