# Generated by Django 6.0.1 on 2026-03-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_conversation_chat_id_conversation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_documents', to='chat.conversation'),
        ),
    ]
