# Generated by Django 6.0.1 on 2026-03-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_alter_conversation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='telegram_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.telegrammessage'),
        ),
    ]
