# Generated by Django 6.0.1 on 2026-03-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_alter_document_telegram_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
            preserve_default=False,
        ),
    ]
