# Generated by Django 6.0.1 on 2026-03-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_telegrammessage_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='conversation',
        ),
    ]
