# Generated by Django 6.0.1 on 2026-04-13 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_remove_telegrammessage_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('chat_id',), name='unique_chat_id_per_conversation'),
        ),
    ]
