# Generated by Django 5.2.13 on 2026-05-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_alter_audiocontent_id_alter_chunk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, default='user_input', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
