# Generated by Django 5.2.13 on 2026-05-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_document_category_document_is_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conv_documents', to='chat.conversation'),
        ),
    ]
