# Generated by Django 5.2.13 on 2026-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_alter_document_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='texts'),
        ),
    ]
