# Generated by Django 5.2.13 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_textcontent_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField()),
                ('unit', models.CharField()),
                ('currency', models.CharField()),
                ('input_cost', models.FloatField()),
                ('output_cost', models.FloatField()),
                ('latency', models.FloatField()),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
            ],
        ),
    ]
