# Generated by Django 5.2.13 on 2026-06-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='completion_content',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='prompt',
            field=models.CharField(null=True),
        ),
    ]
