# Generated by Django 5.2.13 on 2026-06-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_cost_completion_content_cost_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RagComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField()),
                ('input_text', models.CharField(null=True)),
                ('output_text', models.CharField(null=True)),
                ('model', models.CharField(null=True)),
                ('unit', models.CharField(null=True)),
                ('currency', models.CharField(null=True)),
                ('embedding_cost', models.FloatField(null=True)),
                ('input_cost', models.FloatField(null=True)),
                ('output_cost', models.FloatField(null=True)),
                ('latency', models.FloatField()),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('ragpipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ragpipeline')),
            ],
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
