# Generated by Django 5.2.13 on 2026-06-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_ragpipeline_ragcomponent_delete_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragcomponent',
            name='unit',
        ),
    ]
