# Generated by Django 5.2.13 on 2026-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0050_remove_ragcomponent_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='textcontent',
            constraint=models.UniqueConstraint(fields=('content',), name='unique_content_per_textcontent'),
        ),
    ]
