# Generated by Django 5.2.13 on 2026-06-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0052_alter_documentsource_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.documentsource'),
        ),
    ]
