# Generated by Django 5.2.13 on 2026-06-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0053_alter_document_document_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='conversation',
        ),
        migrations.AlterField(
            model_name='document',
            name='telegram_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.telegrammessage'),
        ),
    ]
