# Generated by Django 5.2.13 on 2026-06-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0054_remove_conversation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragcomponent',
            name='ragpipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ragcomponents', to='chat.ragpipeline'),
        ),
    ]
